<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workshopId = Category::where('slug', 'workshop')->value('id') ?? 1;
        $seminarId = Category::where('slug', 'seminar')->value('id') ?? 2;
        $kompetisiId = Category::where('slug', 'kompetisi')->value('id') ?? 3;

        Activity::query()->forceDelete();

        Activity::query()->insert([
            [
                'category_id' => $workshopId,
                'code' => 'ACT-001',
                'title' => 'Workshop Git & GitHub Advanced',
                'description' => 'Latihan kolaborasi repository, branching strategy, dan resolving conflicts.',
                'start_at' => '2026-10-05',
                'end_at' => '2026-10-06',
                'location' => 'Lab Komputer 1',
                'capacity' => 40,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminarId,
                'code' => 'ACT-002',
                'title' => 'Seminar Web Quality & Architecture',
                'description' => 'Pengenalan maintainability, static analysis, dan testing pada Laravel.',
                'start_at' => '2026-10-12',
                'end_at' => '2026-10-12',
                'location' => 'Auditorium Gedung D',
                'capacity' => 150,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshopId,
                'code' => 'ACT-003',
                'title' => 'Sesi Praktikum Modul 3 Special Challenge',
                'description' => 'Pengerjaan Advanced CRUD, Data Integrity, dan Relasional Eloquent.',
                'start_at' => '2026-10-15',
                'end_at' => '2026-10-16',
                'location' => 'Lab Rekayasa Perangkat Lunak',
                'capacity' => 35,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminarId,
                'code' => 'ACT-004',
                'title' => 'Review Desain Arsitektur Perangkat Lunak',
                'description' => 'Diskusi pembagian layer controller, service, domain invariant, dan database constraint.',
                'start_at' => '2026-10-20',
                'end_at' => '2026-10-20',
                'location' => 'Ruang Teori 2',
                'capacity' => 60,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $kompetisiId,
                'code' => 'ACT-005',
                'title' => 'Hackathon Web Development 2026',
                'description' => 'Kompetisi pembuatan aplikasi web terintegrasi 24 jam.',
                'start_at' => '2026-11-01',
                'end_at' => '2026-11-02',
                'location' => 'Hall Utama Kampus',
                'capacity' => 100,
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshopId,
                'code' => 'ACT-006',
                'title' => 'Workshop Docker & Containerization',
                'description' => 'Manajemen container, image building, dan orkestrasi service.',
                'start_at' => '2026-11-05',
                'end_at' => '2026-11-06',
                'location' => 'Lab Jaringan Komputer',
                'capacity' => 45,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminarId,
                'code' => 'ACT-007',
                'title' => 'Seminar Artificial Intelligence & Future Tech',
                'description' => 'Tren AI, LLM, dan otomatisasi pengembangan perangkat lunak.',
                'start_at' => '2026-11-10',
                'end_at' => '2026-11-10',
                'location' => 'Auditorium Gedung D',
                'capacity' => 200,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $kompetisiId,
                'code' => 'ACT-008',
                'title' => 'Lomba UI/UX Design Competition',
                'description' => 'Perancangan prototipe aplikasi mobile responsif dan ramah pengguna.',
                'start_at' => '2026-11-15',
                'end_at' => '2026-11-16',
                'location' => 'Studio Desain Multimedia',
                'capacity' => 80,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshopId,
                'code' => 'ACT-009',
                'title' => 'Bootcamp Laravel API & Microservices',
                'description' => 'Pembangunan RESTful API berstandar OpenAPI dan autentikasi token.',
                'start_at' => '2026-11-20',
                'end_at' => '2026-11-22',
                'location' => 'Lab Komputer 2',
                'capacity' => 50,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminarId,
                'code' => 'ACT-010',
                'title' => 'Tech Talk: Cybersecurity in Modern Era',
                'description' => 'Strategi mitigasi serangan siber dan keamanan data transaksi.',
                'start_at' => '2026-11-25',
                'end_at' => '2026-11-25',
                'location' => 'Ruang Teori 1',
                'capacity' => 120,
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshopId,
                'code' => 'ACT-011',
                'title' => 'Workshop Cloud Computing with GCP & AWS',
                'description' => 'Pengenalan deployment serverless dan konfigurasi bucket penyimpanan.',
                'start_at' => '2026-12-01',
                'end_at' => '2026-12-02',
                'location' => 'Lab Cloud Computing',
                'capacity' => 35,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $kompetisiId,
                'code' => 'ACT-012',
                'title' => 'Coding Championship Mahasiswa Nasional',
                'description' => 'Kompetisi competitive programming tingkat perguruan tinggi.',
                'start_at' => '2026-12-05',
                'end_at' => '2026-12-05',
                'location' => 'Online Platform',
                'capacity' => 150,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminarId,
                'code' => 'ACT-013',
                'title' => 'Seminar Database Optimization & Scaling',
                'description' => 'Teknik indexing, profiling query, dan partitioning basis data relasional.',
                'start_at' => '2026-12-10',
                'end_at' => '2026-12-10',
                'location' => 'Ruang Teori 3',
                'capacity' => 90,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshopId,
                'code' => 'ACT-014',
                'title' => 'Workshop DevOps CI/CD Pipeline',
                'description' => 'Otomatisasi build, test, dan delivery menggunakan GitHub Actions.',
                'start_at' => '2026-12-15',
                'end_at' => '2026-12-16',
                'location' => 'Lab Rekayasa Perangkat Lunak',
                'capacity' => 40,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $kompetisiId,
                'code' => 'ACT-015',
                'title' => 'Grand Final Proyek Web Showcase',
                'description' => 'Presentasi karya akhir dan evaluasi proyek web semester.',
                'start_at' => '2026-12-20',
                'end_at' => '2026-12-20',
                'location' => 'Auditorium Utama',
                'capacity' => 250,
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
